import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { BrowserRouter as Router, Routes, Route } from 'react-router-dom';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { Bot, Home, Settings } from 'lucide-react';
const queryClient = new QueryClient();
function App() {
    return (_jsx(QueryClientProvider, { client: queryClient, children: _jsx(Router, { children: _jsxs("div", { className: 'min-h-screen bg-gray-50', children: [_jsx("header", { className: 'bg-white shadow-sm border-b', children: _jsx("div", { className: 'max-w-7xl mx-auto px-4 sm:px-6 lg:px-8', children: _jsxs("div", { className: 'flex justify-between items-center py-4', children: [_jsxs("div", { className: 'flex items-center space-x-2', children: [_jsx(Bot, { className: 'h-8 w-8 text-blue-600' }), _jsx("h1", { className: 'text-xl font-bold text-gray-900', children: "AI Testing Agent" })] }), _jsxs("nav", { className: 'flex space-x-8', children: [_jsxs("a", { href: '/', className: 'text-gray-600 hover:text-gray-900 flex items-center space-x-1', children: [_jsx(Home, { className: 'h-4 w-4' }), _jsx("span", { children: "Dashboard" })] }), _jsxs("a", { href: '/settings', className: 'text-gray-600 hover:text-gray-900 flex items-center space-x-1', children: [_jsx(Settings, { className: 'h-4 w-4' }), _jsx("span", { children: "Settings" })] })] })] }) }) }), _jsx("main", { className: 'max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8', children: _jsxs(Routes, { children: [_jsx(Route, { path: '/', element: _jsx(Dashboard, {}) }), _jsx(Route, { path: '/settings', element: _jsx(SettingsPage, {}) })] }) })] }) }) }));
}
function Dashboard() {
    return (_jsxs("div", { children: [_jsx("h2", { className: 'text-2xl font-bold text-gray-900 mb-6', children: "Dashboard" }), _jsxs("div", { className: 'grid grid-cols-1 md:grid-cols-3 gap-6', children: [_jsxs("div", { className: 'bg-white p-6 rounded-lg shadow', children: [_jsx("h3", { className: 'text-lg font-medium text-gray-900 mb-2', children: "Web Application Analysis" }), _jsx("p", { className: 'text-gray-600 mb-4', children: "Discover and analyze web applications to identify testable elements." }), _jsx("button", { className: 'bg-blue-600 text-white px-4 py-2 rounded hover:bg-blue-700', children: "Start Analysis" })] }), _jsxs("div", { className: 'bg-white p-6 rounded-lg shadow', children: [_jsx("h3", { className: 'text-lg font-medium text-gray-900 mb-2', children: "Test Generation" }), _jsx("p", { className: 'text-gray-600 mb-4', children: "Automatically generate comprehensive test cases using AI." }), _jsx("button", { className: 'bg-green-600 text-white px-4 py-2 rounded hover:bg-green-700', children: "Generate Tests" })] }), _jsxs("div", { className: 'bg-white p-6 rounded-lg shadow', children: [_jsx("h3", { className: 'text-lg font-medium text-gray-900 mb-2', children: "Test Execution" }), _jsx("p", { className: 'text-gray-600 mb-4', children: "Run automated tests and view detailed results." }), _jsx("button", { className: 'bg-purple-600 text-white px-4 py-2 rounded hover:bg-purple-700', children: "Run Tests" })] })] })] }));
}
function SettingsPage() {
    return (_jsxs("div", { children: [_jsx("h2", { className: 'text-2xl font-bold text-gray-900 mb-6', children: "Settings" }), _jsx("div", { className: 'bg-white p-6 rounded-lg shadow', children: _jsx("p", { className: 'text-gray-600', children: "Settings page coming soon!" }) })] }));
}
export default App;
